---
- hosts: bot
  tasks:
    - name: Clone of a single branch
      git:
        repo: https://github.com/pkilipko/block4.git
        dest: /home/user/app
        version: ansible
        update: yes
    - name: Install specified python requirements
      pip:
        requirements: /home/user/app/requirements.txt
        virtualenv: /home/user/venv
        virtualenv_python: python3.11
        state: present
    - name: Copy file with permissions
      copy:
        src: /home/user/block-4-gh/block4/.env
        dest: /home/user/app/.env
        owner: user
        group: user
        mode: '0644'
    - name: Start script in background with Asynchronous actions and polling
      command: nohup /home/user/venv/bin/python3 block-2.py &
      args:
        chdir: "/home/user/app/"
      async: 9999
      poll: 0

- hosts: primary
  become: True
  tasks:
    - name: Install DB
      apt:
        pkg:
        - postgresql
        - postgresql-contrib
        state: present
        update_cache: yes
    - name: Copy config file
      copy:
        src: /home/user/block-4-gh/block4/postgresql.conf
        dest: /etc/postgresql/15/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'
    - name: Copy config file
      copy:
        src: /home/user/block-4-gh/block4/pg_hba.conf
        dest: /etc/postgresql/15/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0644'
    - name: Restart DB daemon
      service:
        name: postgresql
        state: restarted
    - name: Create DB
      become_user: postgres
      postgresql_db:
        name: practice
        state: present
        login_user: postgres
    - name: Copy schema to public place & Change file ownership, group and permissions
      ansible.builtin.copy:
        remote_src: true
        src: "/home/user/app/00_init.sql"
        dest: /tmp/00_init.sql
        owner: postgres
        group: postgres
        mode: '0644'
    - name: Apply DB schema
      command: sudo -u postgres psql -d practice -f "/tmp/00_init.sql"

- hosts: replica
  become: True
  tasks:
    - name: Install DB
      apt:
        pkg:
        - postgresql
        - postgresql-contrib
        state: present
        update_cache: yes
    - name: Copy config file
      copy:
        src: /home/user/block-4-gh/block4/postgresql-repl.conf
        dest: /etc/postgresql/15/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'
    - name: Stop DB daemon
      service:
        name: postgresql
        state: stopped
    - name: Clear data
      file:
        path: /var/lib/postgresql/15/main/
        state: absent
    - name: Start DB daemon
      service:
        name: postgresql
        state: started
    - name: Take a base backup of a PostgreSQL cluster
      become: yes
      become_user: postgres
      command: pg_basebackup -R -h 192.168.11.138 -U replicator -D /var/lib/postgresql/15/main -P
      environment:
        PGPASSWORD: "replicator_password"
      register: pg_basebackup_result
      failed_when: pg_basebackup_result.rc != 0
      changed_when: False
